"""
Django settings for NewsPaper project.

Generated by 'django-admin startproject' using Django 3.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

import os
from pathlib import Path
from .functions import get_env


# Build paths inside the project like this: BASE_DIR / 'subdir'.
# import django.contrib.flatpages.middleware

BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-$7cqmv=v5#uf*c7lol(sw$98ldcp5zna4sydf-9)5ku3+&3dnk'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

SITE_ID = 1

# LOGGING_CONFIG = None

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,  # Включение/отключение настроек логирования Django
    'style': '{',
    'formatters': {
        'f_debug': {
            'format': '%(asctime)s %(levelname)s %(message)s'
        },
        'f_warning': {
            'format': '%(asctime)s %(levelname)s %(message)s %(pathname)s'
        },
        'f_error': {
            'format': '%(asctime)s %(levelname)s %(message)s %(pathname)s %(exc_info)s'
        },
        'f_error_noexc': {
            'format': '%(asctime)s %(levelname)s %(message)s %(pathname)s'
        },
        'ff_general_info': {
            'format': '%(asctime)s %(levelname)s %(module)s %(message)s'
        },
    },
    'filters': {
        'require_debug_true': {
            '()': 'django.utils.log.RequireDebugTrue',
        },
        'require_debug_false': {
            '()': 'django.utils.log.RequireDebugFalse',
        },
    },
    'handlers': {
        'console_debug': {
            'level': 'DEBUG',
            'filters': ['require_debug_true'],
            'class': 'logging.StreamHandler',
            'formatter': 'f_debug',
        },
        'console_warning': {
            'level': 'WARNING',
            'filters': ['require_debug_true'],
            'class': 'logging.StreamHandler',
            'formatter': 'f_warning',
        },
        'console_error': {
            'level': 'ERROR',
            'filters': ['require_debug_true'],
            'class': 'logging.StreamHandler',
            'formatter': 'f_error',
        },
        # В файл general.log должны выводиться сообщения уровня INFO
        # и выше только с указанием времени, уровня логирования, модуля,
        # в котором возникло сообщение (аргумент module) и само сообщение.
        # Сюда также попадают сообщения с регистратора django.
        'gen_file_info': {
            'level': 'INFO',
            'filters': ['require_debug_false'],
            'class': 'logging.FileHandler',
            'formatter': 'ff_general_info',
            'filename': os.path.join(BASE_DIR, 'logs/general.log'),
        },
        # В файл errors.log должны выводиться сообщения только уровня ERROR и CRITICAL.
        # В сообщении указывается время, уровень логирования, само сообщение,
        # путь к источнику сообщения и стэк ошибки. В этот файл должны попадать сообщения
        # только из логгеров django.request, django.server, django.template, django.db_backends.
        'err_file_info': {
            'level': 'ERROR',
            'filters': ['require_debug_true'],
            'class': 'logging.FileHandler',
            'formatter': 'f_error',
            'filename': os.path.join(BASE_DIR, 'logs/errors.log'),
        },
        # В файл security.log должны попадать только сообщения,
        # связанные с безопасностью, а значит только из логгера django.security.
        # Формат вывода предполагает время, уровень логирования, модуль и сообщение.
        'sec_file_info': {
            'level': 'DEBUG',
            'filters': ['require_debug_true'],
            'class': 'logging.FileHandler',
            'formatter': 'ff_general_info',
            'filename': os.path.join(BASE_DIR, 'logs/security.log'),
        },
        # На почту должны отправляться сообщения уровней ERROR и выше
        # из django.request и django.server по формату, как в errors.log,
        # но без стэка ошибок.
        'mail_admins': {
            'level': 'ERROR',
            'filters': ['require_debug_false'],
            'class': 'django.utils.log.AdminEmailHandler',
            'formatter': 'f_error_noexc',
        },
    },
    'loggers': {
        'News.views': {
            'handlers': ['console_debug', 'console_warning', 'console_error'],
            'level': 'DEBUG',
            'propagate': False,  # Включение/отключение обработки логерами более высокого уровня
        },
        'django': {
            'handlers': ['console_debug', 'console_warning', 'console_error', 'gen_file_info'],
            'propagate': True,
        },
        'django.request': {
            'handlers': ['err_file_info', 'mail_admins'],
            'propagate': False,
        },
        'django.server': {
            'handlers': ['err_file_info', 'mail_admins'],
            'propagate': False,
        },
        'django.template': {
            'handlers': ['err_file_info'],
            'propagate': False,
        },
        'django.db_backends': {
            'handlers': ['err_file_info'],
            'propagate': False,
        },
        'django.security': {
            'handlers': ['sec_file_info'],
            'propagate': False,
        },
    },
}

AUTHENTICATION_BACKENDS = [
    # Needed to login by username in Django admin, regardless of `allauth`
    'django.contrib.auth.backends.ModelBackend',
    # `allauth` specific authentication methods, such as login by e-mail
    'allauth.account.auth_backends.AuthenticationBackend',
]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'News.apps.NewsConfig',
    'accounts',
    'django_filters',
    'django.contrib.sites',
    'django.contrib.flatpages',
    'sign',
    'protect',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    # Выбранный нами провайдер
    'allauth.socialaccount.providers.google',
    'django_apscheduler',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.contrib.flatpages.middleware.FlatpageFallbackMiddleware',
]

ROOT_URLCONF = 'NewsPaper.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'NewsPaper.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = False

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

STATICFILES_DIRS = [
    BASE_DIR / 'static'
]

# LOGIN_URL = 'sign/login/'
LOGIN_URL = '/accounts/login/'
LOGIN_REDIRECT_URL = '/'

ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_EMAIL_CONFIRMATION_REQUIRED = True
ACCOUNT_AUTHENTICATION_METHOD = 'email'
ACCOUNT_EMAIL_VERIFICATION = 'none'
ACCOUNT_FORMS = {'signup': 'sign.forms.BasicSignupForm'}

ACCOUNT_LOGIN_URL = 'News:account_login'
ACCOUNT_EMAIL_CONFIRMATION_ANONYMOUS_REDIRECT_URL = ACCOUNT_LOGIN_URL
ACCOUNT_PASSWORD_RESET_REDIRECT_URL = ACCOUNT_LOGIN_URL
ACCOUNT_EMAIL_CONFIRMATION_URL = "News:account_confirm_email"
ACCOUNT_SETTINGS_REDIRECT_URL = 'News:account_settings'
ACCOUNT_PASSWORD_CHANGE_REDIRECT_URL = "News:account_password"

# DIR_STATE = os.getenv('EMAIL_HOST')
EMAIL_HOST = get_env('EMAIL_HOST')
EMAIL_PORT = get_env('EMAIL_PORT')
EMAIL_HOST_USER = get_env('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = get_env('EMAIL_HOST_PASSWORD')
EMAIL_USE_SSL = get_env('EMAIL_USE_SSL')
EMAIL_FROM_USER = get_env('EMAIL_FROM_USER')

DEFAULT_FROM_EMAIL = EMAIL_FROM_USER

# формат даты, которую будет воспринимать наш задачник
APSCHEDULER_DATETIME_FORMAT = "N j, Y, f:s a"
# Отмена при невыполнении (секунды)
APSCHEDULER_RUN_NOW_TIMEOUT = 25

CELERY_BROKER_URL = 'redis://' + get_env('HOST') + ':' + get_env('PORT')
CELERY_RESULT_BACKEND = 'redis://' + get_env('HOST') + ':' + get_env('PORT')
CELERY_ACCEPT_CONTENT = ['application/json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
