# Generated by Django 3.2.8 on 2021-11-20 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0002_user_user_django'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailingLists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='News.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='News.user')),
            ],
        ),
    ]
