# Generated by Django 3.2.8 on 2021-11-23 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0003_mailinglists'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailinglists',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='News.category'),
        ),
    ]
